---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: remyuilicious/k8control:delete-pods
    imagePullPolicy: Always
  serviceAccountName: monitor-pods-acc
