---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reaper-pods-acc
  namespace: webdriver-grid-w1dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reap-pods
  namespace: webdriver-grid-w1dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reap-pods
  namespace: webdriver-grid-w1dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reap-pods
subjects:
  - kind: ServiceAccount
    name: reaper-pods-acc
    namespace: webdriver-grid-w1dev

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-reaper
  namespace: webdriver-grid-w1dev
spec:
  containers:
  - name: pod-reaper
    image: remyuilicious/k8control:delete-pods
    imagePullPolicy: Always
    env:
      - name: NAMESPACE
        value: "webdriver-grid-w1dev"
      - name: TARGETPOD
        value: "edge2019"
      - name: DEBUG
        value: "false"
      - name: LOG_LEVEL
        value: "error"
  serviceAccountName: reaper-pods-acc
