---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-pods-acc
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-pods
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-pods
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-pods
subjects:
  - kind: ServiceAccount
    name: monitor-pods-acc
    namespace: default

---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
  namespace: default
spec:
  containers:
  - name: shell-operator
    image: remyuilicious/k8control:delete-pods
    imagePullPolicy: Always
    env:
      - name: TARGET
        value: ""
      - name: DEBUG
        value: "true"
  serviceAccountName: monitor-pods-acc
