---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-pods-acc
  namespace:  test-delete-pods

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-pods
  namespace:  test-delete-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-pods
  namespace:  test-delete-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-pods
subjects:
  - kind: ServiceAccount
    name: monitor-pods-acc
    namespace:  test-delete-pods

---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
  namespace:  test-delete-pods
spec:
  containers:
  - name: shell-operator
    image: remyuilicious/k8control:delete-pods
    imagePullPolicy: Always
  serviceAccountName: monitor-pods-acc
